// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Sidebar': string;
  'collapsed': string;
  'lang': string;
  'switchers': string;
}
export const cssExports: CssExports;
export default cssExports;
